### ISSUE TITLE
Looking for F# expert to help

### ISSUE THREAD

**Issue by Oceania2018** [CompositionalIT/Machine-Learning-For-.NET-Developers-Notebook#1]
I just saw a technical [article ](https://www.compositional-it.com/news-blog/machine-learning-in-net-pt-2-tensorflow/)you wrote. Thank you very much for your attention and use of the machine learning library provided by SciSharp. It mentioned that there is a problem running under .NET 6.0. This bug has been fixed in the latest version. You can test it again when you have time. In addition, I found that you are using F#. If possible, can you help us to fix our F# [example ](https://github.com/SciSharp/SciSharp-Stack-Examples)and upgrade to the latest version of TensorFlow.NET. It doesn't matter if you don't want to.

**Comment by isaacabraham** [comment]
Thank you for fixing this! Unfortunately we aren't focusing on ML at the moment so I'm going to close this issue, but thanks for reaching out.
